name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    name: Build, lint, test & analyze
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test
